;
;DCPU-16 ASM Generated by LCC 4.2 (dcpu16-lcc v0.1)
;
JSR _global_main
:_crash
SET PC, _crash
:_global_main
SET PUSH, 0  ;making room on stack for locals
SET I, J
SET J, SP    ;set new frame pointer
SET PUSH, I  ;save previous frame pointer
SET A, 120
JSR _global_malloc
SET [J], A
SET A, _L2
SET B, [J]
JSR _global_printf
SET A, _L3
SET Z, [J]
SET B, [Z]
JSR _global_printf
SET A, 0
:_L1
SET J, POP   ;restore previous frame pointer
SET EX, POP  ;popping locals and register arguments from stack
SET PC, POP
:_L3
DAT 0x0050,0x005B,0x0030,0x005D,0x0020,0x003D,0x0020,0x0025,0x0064,0x000A,0x0000 ;string
:_L2
DAT 0x0050,0x0020,0x003D,0x0020,0x0025,0x0064,0x000A,0x0000 ;string
:_scratch0
DAT 0
:_scratch1
DAT 0
:_scratch2
DAT 0
:_scratch3
DAT 0
:_scratch4
DAT 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
